[package]
name = "texture_issue"
version = "0.1.0"
authors = ["Ben Konz <bkonz@unomaha.edu>"]

[dependencies]
stdweb = "0.4"
serde = "1.0.0"
serde_derive = "1.0.0"
stdweb-derive = "0.4.0"

[build-dependencies]
webgl_generator = "0.1.0"